DEPENDENCY_LIB_NAMES := $(foreach dep,$(filter Lib:%,$(DEPENDENCIES)),$(word 2,$(subst :, ,$(dep))))
DEPENDENCY_LIBS := $(DEPENDENCY_LIB_NAMES:%=lib%-$(CPU).a)
DEPENDENCY_LIB_TARGETS := $(DEPENDENCY_LIBS:%=%.dependency)
DEPENDENCY_LIB_PATHS := $(foreach dep,$(DEPENDENCY_LIB_NAMES),$(BUILD_DIR)/$(dep)/lib$(dep)-$(CPU).a)

DEPENDENCY_EXEC_NAMES := $(foreach dep,$(filter Exec:%,$(DEPENDENCIES)),$(word 2,$(subst :, ,$(dep))))
DEPENDENCY_EXEC_TARGETS := $(DEPENDENCY_EXEC_NAMES:%=%-$(CPU).exec.dependency)

ifeq ($(strip $(NO_GATEWARE_DEPS)),yes)
unexport DEPENDENCY_GATEWARE_TARGETS
else
DEPENDENCY_GATEWARE_NAMES := $(foreach dep,$(filter Gateware:%,$(DEPENDENCIES)),$(word 2,$(subst :, ,$(dep))))
DEPENDENCY_GATEWARE_TARGETS := $(DEPENDENCY_GATEWARE_NAMES:%=%-$(FPGA_DEVICE).gateware.dependency)
endif

ifeq ($(strip $(NO_TOOLS_DEPS)),yes)
unexport DEPENDENCY_TOOL_TARGETS
else
DEPENDENCY_TOOL_NAMES := $(foreach dep,$(filter Tool:%,$(DEPENDENCIES)),$(word 2,$(subst :, ,$(dep))))
DEPENDENCY_TOOL_TARGETS := $(DEPENDENCY_TOOL_NAMES:%=%.tool.dependency)
endif

ifeq ($(strip $(NO_TESTS_DEPS)),yes)
unexport DEPENDENCY_TEST_TARGETS
else
DEPENDENCY_TEST_NAMES := $(foreach dep,$(filter Test:%,$(DEPENDENCIES)),$(word 2,$(subst :, ,$(dep))))
DEPENDENCY_TEST_TARGETS := $(DEPENDENCY_TEST_NAMES:%=%.test.dependency)
endif

ifeq ($(strip $(NO_MAKE_DEPS)),yes)
unexport DEPENDENCY_MAKE_TARGETS
else
DEPENDENCY_MAKE_NAMES := $(foreach dep,$(filter Make:%,$(DEPENDENCIES)),$(word 2,$(subst :, ,$(dep))))
DEPENDENCY_MAKE_TARGETS := $(DEPENDENCY_MAKE_NAMES:%=%.make.dependency)
DEPENDENCY_TARGETS := $(DEPENDENCY_TOOL_TARGETS) $(DEPENDENCY_LIB_TARGETS) $(DEPENDENCY_EXEC_TARGETS) $(DEPENDENCY_GATEWARE_TARGETS) $(DEPENDENCY_MAKE_TARGETS) $(DEPENDENCY_TEST_TARGETS)
$(foreach mod,$(DEPENDENCIES),$(eval DEPENDENCY_PATH_$(word 2,$(subst :, ,$(mod))) = $(abspath $(lastword $(subst :, ,$(mod))))))
endif

NO_TESTS_DEPS ?= $(IN_NO_TESTS_DEPS)
NO_GATEWARE_UPLOAD ?= $(IN_NO_GATEWARE_UPLOAD)
NO_GATEWARE_DEPS ?= $(IN_NO_GATEWARE_DEPS)
NO_TOOLS_DEPS ?= $(IN_NO_TOOLS_DEPS)

# Libs need to be placed in the build dir after building. This is different than a module, it requires a makefile to be present,
# so it is not viable to be used with Arduino libs.
lib%-$(CPU).a.dependency:
ifeq ($(strip $(VERBOSE)),1)
	@$(VMSG) "Building lib$*-$(CPU).a.dependency"
	@$(VCFGMSG) "TARGET:" "$*"
	@$(VCFGMSG) "PATH:" "$(DEPENDENCY_PATH_$*)"
	@$(VCFGMSG) "OPTS:" "$(DEPENDENCY_OPTS_$*)"
	@$(VCFGMSG) "BUILD_OPTS:" "$(BUILD_OPTS)"
	@$(VCFGMSG) "VERBOSE:" "$(VERBOSE)"
	@$(VCFGMSG) "DEBUG:" "$(DEBUG)"
	@$(VCFGMSG) "STARTUP_MAKEFILE:" "$(STARTUP_MAKEFILE)"
	@$(VCFGMSG) "CPU_BASE_TARGET:" "$(CPU_BASE_TARGET)"
	@$(VCFGMSG) "BUILD_DIR:" "$(BUILD_DIR)/$*"
	@$(VCFGMSG) "In CPU_DEVICE:" "$(CPU_DEVICE)"
	@$(VCFGMSG) "In CPU_EXEC_OFFSET:" "$(CPU_EXEC_OFFSET)"
	@$(VCFGMSG) "In CPU_DEVICE_OPTS:" "$(CPU_DEVICE_OPTS)"
	@$(VCFGMSG) "In CFLAGS:" "$(CPU_CFLAGS)"
	@$(VCFGMSG) "In CXXFLAGS:" "$(CPU_CXXFLAGS)"
	@$(VCFGMSG) "In CPPFLAGS:" "$(CPU_CPPFLAGS)"
	@$(VCFGMSG) "In ASMFLAGS:" "$(CPU_ASMFLAGS)"
	@$(VCFGMSG) "In LDFLAGS:" "$(CPU_LDFLAGS)"
	@$(VCFGMSG) "In ARFLAGS:" "$(CPU_ARFLAGS)"
	@$(VCFGMSG) "In OBJCOPYFLAGS:" "$(CPU_OBJCOPYFLAGS)"
	@$(VCFGMSG) "In OPTIMIZE:" "$(CPU_OPTIMIZE)"
	@$(VCFGMSG) "In FPGA_DEVICE:" "$(FPGA_DEVICE)"
	@$(VCFGMSG) "In FPGA_DEVICE_OPTS:" "$(FPGA_DEVICE_OPTS)"
	@$(VCFGMSG) "In NO_TESTS_DEPS:" "$(NO_TESTS_DEPS)"
	@$(VCFGMSG) "In NO_GATEWARE_UPLOAD:" "$(NO_GATEWARE_UPLOAD)"
	@$(VCFGMSG) "In NO_GATEWARE_DEPS:" "$(NO_GATEWARE_DEPS)"
	@$(VCFGMSG) "In NO_TOOLS_DEPS:" "$(NO_TOOLS_DEPS)"
	@$(VCFGMSG) 'MAKECMDGOALS:' '$(MAKECMDGOALS)'
else
	@$(MSG) "[LIB]" "$*"
endif
	$(V)$(MAKE) --directory="$(DEPENDENCY_PATH_$*)" --file="$(DEPENDENCY_PATH_$*)/Makefile" \
 					$(DEPENDENCY_OPTS_$*) 'BUILD_OPTS=$(BUILD_OPTS)' 'VERBOSE=$(VERBOSE)' 'DEBUG=$(DEBUG)' 'CPU_TARGET=$*' \
 					'STARTUP_MAKEFILE=$(STARTUP_MAKEFILE)' 'CPU_BASE_TARGET=$(CPU_BASE_TARGET)' 'BUILD_DIR=$(BUILD_DIR)/$*' \
 					'IN_NO_TESTS_DEPS=$(NO_TESTS_DEPS)' 'IN_NO_GATEWARE_UPLOAD=$(NO_GATEWARE_UPLOAD)' \
 					'IN_NO_GATEWARE_DEPS=$(NO_GATEWARE_DEPS)' 'IN_NO_TOOLS_DEPS=$(NO_TOOLS_DEPS)' \
 					'IN_CPU_DEVICE=$(CPU_DEVICE)' 'IN_CPU_EXEC_OFFSET=$(CPU_EXEC_OFFSET)' 'IN_CPU_DEVICE_OPTS=$(CPU_DEVICE_OPTS)' \
 					'IN_CFLAGS=$(CPU_CFLAGS)' 'IN_CXXFLAGS=$(CPU_CXXFLAGS)' 'IN_CPPFLAGS=$(CPU_CPPFLAGS)' 'IN_ASMFLAGS=$(CPU_ASMFLAGS)' \
 					'IN_LDFLAGS=$(CPU_LDFLAGS)' 'IN_ARFLAGS=$(CPU_ARFLAGS)' 'IN_OBJCOPYFLAGS=$(CPU_OBJCOPYFLAGS)' 'IN_OPTIMIZE=$(CPU_OPTIMIZE)' \
 					'IN_FPGA_DEVICE=$(FPGA_DEVICE)' 'IN_FPGA_DEVICE_OPTS=$(FPGA_DEVICE_OPTS)' \
 					 $(MAKECMDGOALS)

# Executables need to be built and then installed before deploying to CPU, they need to adhere to prefix, so they can be included
# in an image. The idea is to load them onto an SD card and load them into memory at runtime
%-$(CPU).exec.dependency:
ifeq ($(strip $(VERBOSE)),1)
	@$(VMSG) "Building $*-$(CPU).exec.dependency"
	@$(VCFGMSG) "TARGET:" "$*"
	@$(VCFGMSG) "PATH:" "$(DEPENDENCY_PATH_$*)"
	@$(VCFGMSG) "OPTS:" "$(DEPENDENCY_OPTS_$*)"
	@$(VCFGMSG) "BUILD_OPTS:" "$(BUILD_OPTS)"
	@$(VCFGMSG) "VERBOSE:" "$(VERBOSE)"
	@$(VCFGMSG) "DEBUG:" "$(DEBUG)"
	@$(VCFGMSG) "STARTUP_MAKEFILE:" "$(STARTUP_MAKEFILE)"
	@$(VCFGMSG) "CPU_BASE_TARGET:" "$(CPU_BASE_TARGET)"
	@$(VCFGMSG) "BUILD_DIR:" "$(BUILD_DIR)/$*"
	@$(VCFGMSG) "In CPU_DEVICE:" "$(CPU_DEVICE)"
	@$(VCFGMSG) "In CPU_EXEC_OFFSET:" "$(CPU_EXEC_OFFSET)"
	@$(VCFGMSG) "In CPU_DEVICE_OPTS:" "$(CPU_DEVICE_OPTS)"
	@$(VCFGMSG) "In CFLAGS:" "$(CPU_CFLAGS)"
	@$(VCFGMSG) "In CXXFLAGS:" "$(CPU_CXXFLAGS)"
	@$(VCFGMSG) "In CPPFLAGS:" "$(CPU_CPPFLAGS)"
	@$(VCFGMSG) "In ASMFLAGS:" "$(CPU_ASMFLAGS)"
	@$(VCFGMSG) "In LDFLAGS:" "$(CPU_LDFLAGS)"
	@$(VCFGMSG) "In ARFLAGS:" "$(CPU_ARFLAGS)"
	@$(VCFGMSG) "In OBJCOPYFLAGS:" "$(CPU_OBJCOPYFLAGS)"
	@$(VCFGMSG) "In OPTIMIZE:" "$(CPU_OPTIMIZE)"
	@$(VCFGMSG) "In FPGA_DEVICE:" "$(FPGA_DEVICE)"
	@$(VCFGMSG) "In FPGA_DEVICE_OPTS:" "$(FPGA_DEVICE_OPTS)"
	@$(VCFGMSG) "In NO_TESTS_DEPS:" "$(NO_TESTS_DEPS)"
	@$(VCFGMSG) "In NO_GATEWARE_UPLOAD:" "$(NO_GATEWARE_UPLOAD)"
	@$(VCFGMSG) "In NO_GATEWARE_DEPS:" "$(NO_GATEWARE_DEPS)"
	@$(VCFGMSG) "In NO_TOOLS_DEPS:" "$(NO_TOOLS_DEPS)"
	@$(VCFGMSG) 'MAKECMDGOALS:' '$(MAKECMDGOALS)'
else
	@$(MSG) "[EXEC]" "$*"
endif
	$(V)$(MAKE) --directory="$(DEPENDENCY_PATH_$*)" --file="$(DEPENDENCY_PATH_$*)/Makefile" \
 					$(DEPENDENCY_OPTS_$*) 'BUILD_OPTS=$(BUILD_OPTS)' 'VERBOSE=$(VERBOSE)' 'DEBUG=$(DEBUG)' 'CPU_TARGET=$*' \
 					'STARTUP_MAKEFILE=$(STARTUP_MAKEFILE)' 'CPU_BASE_TARGET=$(CPU_BASE_TARGET)' 'BUILD_DIR=$(BUILD_DIR)/$*' \
 					'IN_NO_TESTS_DEPS=$(NO_TESTS_DEPS)' 'IN_NO_GATEWARE_UPLOAD=$(NO_GATEWARE_UPLOAD)' \
 					'IN_NO_GATEWARE_DEPS=$(NO_GATEWARE_DEPS)' 'IN_NO_TOOLS_DEPS=$(NO_TOOLS_DEPS)' \
 					'IN_CPU_DEVICE=$(CPU_DEVICE)' 'IN_CPU_EXEC_OFFSET=$(CPU_EXEC_OFFSET)' 'IN_CPU_DEVICE_OPTS=$(CPU_DEVICE_OPTS)' \
 					'IN_CFLAGS=$(CPU_CFLAGS)' 'IN_CXXFLAGS=$(CPU_CXXFLAGS)' 'IN_CPPFLAGS=$(CPU_CPPFLAGS)' 'IN_ASMFLAGS=$(CPU_ASMFLAGS)' \
 					'IN_LDFLAGS=$(CPU_LDFLAGS)' 'IN_ARFLAGS=$(CPU_ARFLAGS)' 'IN_OBJCOPYFLAGS=$(CPU_OBJCOPYFLAGS)' 'IN_OPTIMIZE=$(CPU_OPTIMIZE)' \
 					'IN_FPGA_DEVICE=$(FPGA_DEVICE)' 'IN_FPGA_DEVICE_OPTS=$(FPGA_DEVICE_OPTS)' \
 					 $(MAKECMDGOALS)

# Gateware needs to be uploaded when deploying, but only directly from its directory if to flash or during CPU install if JTAG
%-$(FPGA_DEVICE).gateware.dependency:
ifeq ($(strip $(VERBOSE)),1)
	@$(VMSG) "Building $*-$(FPGA_DEVICE).gateware.dependency"
	@$(VCFGMSG) "TARGET:" "$*"
	@$(VCFGMSG) "PATH:" "$(DEPENDENCY_PATH_$*)"
	@$(VCFGMSG) "OPTS:" "$(DEPENDENCY_OPTS_$*)"
	@$(VCFGMSG) "BUILD_OPTS:" "$(BUILD_OPTS)"
	@$(VCFGMSG) "VERBOSE:" "$(VERBOSE)"
	@$(VCFGMSG) "DEBUG:" "$(DEBUG)"
	@$(VCFGMSG) "STARTUP_MAKEFILE:" "$(STARTUP_MAKEFILE)"
	@$(VCFGMSG) "CPU_BASE_TARGET:" "$(CPU_BASE_TARGET)"
	@$(VCFGMSG) "BUILD_DIR:" "$(BUILD_DIR)/$*"
	@$(VCFGMSG) "In CPU_DEVICE:" "$(CPU_DEVICE)"
	@$(VCFGMSG) "In CPU_EXEC_OFFSET:" "$(CPU_EXEC_OFFSET)"
	@$(VCFGMSG) "In CPU_DEVICE_OPTS:" "$(CPU_DEVICE_OPTS)"
	@$(VCFGMSG) "In CFLAGS:" "$(CPU_CFLAGS)"
	@$(VCFGMSG) "In CXXFLAGS:" "$(CPU_CXXFLAGS)"
	@$(VCFGMSG) "In CPPFLAGS:" "$(CPU_CPPFLAGS)"
	@$(VCFGMSG) "In ASMFLAGS:" "$(CPU_ASMFLAGS)"
	@$(VCFGMSG) "In LDFLAGS:" "$(CPU_LDFLAGS)"
	@$(VCFGMSG) "In ARFLAGS:" "$(CPU_ARFLAGS)"
	@$(VCFGMSG) "In OBJCOPYFLAGS:" "$(CPU_OBJCOPYFLAGS)"
	@$(VCFGMSG) "In OPTIMIZE:" "$(CPU_OPTIMIZE)"
	@$(VCFGMSG) "In FPGA_DEVICE:" "$(FPGA_DEVICE)"
	@$(VCFGMSG) "In FPGA_DEVICE_OPTS:" "$(FPGA_DEVICE_OPTS)"
	@$(VCFGMSG) "In NO_TESTS_DEPS:" "$(NO_TESTS_DEPS)"
	@$(VCFGMSG) "In NO_GATEWARE_UPLOAD:" "$(NO_GATEWARE_UPLOAD)"
	@$(VCFGMSG) "In NO_GATEWARE_DEPS:" "$(NO_GATEWARE_DEPS)"
	@$(VCFGMSG) "In NO_TOOLS_DEPS:" "$(NO_TOOLS_DEPS)"
	@$(VCFGMSG) 'MAKECMDGOALS:' '$(MAKECMDGOALS)'
else
	@$(MSG) "[GATE]" "$*"
endif
	$(V)$(MAKE) --directory="$(DEPENDENCY_PATH_$*)" --file="$(DEPENDENCY_PATH_$*)/Makefile" \
 					$(DEPENDENCY_OPTS_$*) 'BUILD_OPTS=$(BUILD_OPTS)' 'VERBOSE=$(VERBOSE)' 'DEBUG=$(DEBUG)' 'CPU_TARGET=$*' \
 					'STARTUP_MAKEFILE=$(STARTUP_MAKEFILE)' 'CPU_BASE_TARGET=$(CPU_BASE_TARGET)' 'BUILD_DIR=$(BUILD_DIR)/$*' \
 					'IN_NO_TESTS_DEPS=$(NO_TESTS_DEPS)' 'IN_NO_GATEWARE_UPLOAD=$(NO_GATEWARE_UPLOAD)' \
 					'IN_NO_GATEWARE_DEPS=$(NO_GATEWARE_DEPS)' 'IN_NO_TOOLS_DEPS=$(NO_TOOLS_DEPS)' \
 					'IN_CPU_DEVICE=$(CPU_DEVICE)' 'IN_CPU_EXEC_OFFSET=$(CPU_EXEC_OFFSET)' 'IN_CPU_DEVICE_OPTS=$(CPU_DEVICE_OPTS)' \
 					'IN_CFLAGS=$(CPU_CFLAGS)' 'IN_CXXFLAGS=$(CPU_CXXFLAGS)' 'IN_CPPFLAGS=$(CPU_CPPFLAGS)' 'IN_ASMFLAGS=$(CPU_ASMFLAGS)' \
 					'IN_LDFLAGS=$(CPU_LDFLAGS)' 'IN_ARFLAGS=$(CPU_ARFLAGS)' 'IN_OBJCOPYFLAGS=$(CPU_OBJCOPYFLAGS)' 'IN_OPTIMIZE=$(CPU_OPTIMIZE)' \
 					'IN_FPGA_DEVICE=$(FPGA_DEVICE)' 'IN_FPGA_DEVICE_OPTS=$(FPGA_DEVICE_OPTS)' \
 					 $(MAKECMDGOALS)

# Tools need to be built, but for the current platform, not for the target platform, they don't need to run install
%.tool.dependency:
ifeq ($(strip $(VERBOSE)),1)
	@$(VMSG) "Building $*.tool.dependency"
	@$(VCFGMSG) "TARGET:" "$*"
	@$(VCFGMSG) "PATH:" "$(DEPENDENCY_PATH_$*)"
	@$(VCFGMSG) "OPTS:" "$(DEPENDENCY_OPTS_$*)"
	@$(VCFGMSG) "BUILD_OPTS:" "$(BUILD_OPTS)"
	@$(VCFGMSG) "VERBOSE:" "$(VERBOSE)"
	@$(VCFGMSG) "DEBUG:" "$(DEBUG)"
	@$(VCFGMSG) "STARTUP_MAKEFILE:" "$(STARTUP_MAKEFILE)"
	@$(VCFGMSG) "CPU_BASE_TARGET:" "$(CPU_BASE_TARGET)"
	@$(VCFGMSG) "BUILD_DIR:" "$(BUILD_DIR)/$*"
	@$(VCFGMSG) "In CPU_DEVICE:" "$(CPU_DEVICE)"
	@$(VCFGMSG) "In CPU_EXEC_OFFSET:" "$(CPU_EXEC_OFFSET)"
	@$(VCFGMSG) "In CPU_DEVICE_OPTS:" "$(CPU_DEVICE_OPTS)"
	@$(VCFGMSG) "In CFLAGS:" "$(CPU_CFLAGS)"
	@$(VCFGMSG) "In CXXFLAGS:" "$(CPU_CXXFLAGS)"
	@$(VCFGMSG) "In CPPFLAGS:" "$(CPU_CPPFLAGS)"
	@$(VCFGMSG) "In ASMFLAGS:" "$(CPU_ASMFLAGS)"
	@$(VCFGMSG) "In LDFLAGS:" "$(CPU_LDFLAGS)"
	@$(VCFGMSG) "In ARFLAGS:" "$(CPU_ARFLAGS)"
	@$(VCFGMSG) "In OBJCOPYFLAGS:" "$(CPU_OBJCOPYFLAGS)"
	@$(VCFGMSG) "In OPTIMIZE:" "$(CPU_OPTIMIZE)"
	@$(VCFGMSG) "In FPGA_DEVICE:" "$(FPGA_DEVICE)"
	@$(VCFGMSG) "In FPGA_DEVICE_OPTS:" "$(FPGA_DEVICE_OPTS)"
	@$(VCFGMSG) "In NO_TESTS_DEPS:" "$(NO_TESTS_DEPS)"
	@$(VCFGMSG) "In NO_GATEWARE_UPLOAD:" "$(NO_GATEWARE_UPLOAD)"
	@$(VCFGMSG) "In NO_GATEWARE_DEPS:" "$(NO_GATEWARE_DEPS)"
	@$(VCFGMSG) "In NO_TOOLS_DEPS:" "$(NO_TOOLS_DEPS)"
	@$(VCFGMSG) 'MAKECMDGOALS:' '$(MAKECMDGOALS)'
else
	@$(MSG) "[TOOL]" "$*"
endif
	$(V)$(MAKE) --directory="$(DEPENDENCY_PATH_$*)" --file="$(DEPENDENCY_PATH_$*)/Makefile" $(DEPENDENCY_OPTS_$*) \
 					$(DEPENDENCY_OPTS_$*) 'BUILD_OPTS=$(BUILD_OPTS)' 'VERBOSE=$(VERBOSE)' 'DEBUG=$(DEBUG)' 'CPU_TARGET=$*' \
 					'STARTUP_MAKEFILE=$(STARTUP_MAKEFILE)' 'CPU_BASE_TARGET=$(CPU_BASE_TARGET)' 'BUILD_DIR=$(BUILD_DIR)/$*' \
 					'IN_NO_TESTS_DEPS=$(NO_TESTS_DEPS)' 'IN_NO_GATEWARE_UPLOAD=$(NO_GATEWARE_UPLOAD)' \
 					'IN_NO_GATEWARE_DEPS=$(NO_GATEWARE_DEPS)' 'IN_NO_TOOLS_DEPS=$(NO_TOOLS_DEPS)' \
 					'IN_CPU_DEVICE=$(CPU_DEVICE)' 'IN_CPU_EXEC_OFFSET=$(CPU_EXEC_OFFSET)' 'IN_CPU_DEVICE_OPTS=$(CPU_DEVICE_OPTS)' \
 					'IN_CFLAGS=$(CPU_CFLAGS)' 'IN_CXXFLAGS=$(CPU_CXXFLAGS)' 'IN_CPPFLAGS=$(CPU_CPPFLAGS)' 'IN_ASMFLAGS=$(CPU_ASMFLAGS)' \
 					'IN_LDFLAGS=$(CPU_LDFLAGS)' 'IN_ARFLAGS=$(CPU_ARFLAGS)' 'IN_OBJCOPYFLAGS=$(CPU_OBJCOPYFLAGS)' 'IN_OPTIMIZE=$(CPU_OPTIMIZE)' \
 					'IN_FPGA_DEVICE=$(FPGA_DEVICE)' 'IN_FPGA_DEVICE_OPTS=$(FPGA_DEVICE_OPTS)' \
 					 $(MAKECMDGOALS)

# Tests need to be built, but for the current platform, not for the target platform, they then need to be run upon make directly
%.test.dependency:
ifeq ($(strip $(VERBOSE)),1)
	@$(VMSG) "Building $*.test.dependency"
	@$(VCFGMSG) "TARGET:" "$*"
	@$(VCFGMSG) "PATH:" "$(DEPENDENCY_PATH_$*)"
	@$(VCFGMSG) "OPTS:" "$(DEPENDENCY_OPTS_$*)"
	@$(VCFGMSG) "BUILD_OPTS:" "$(BUILD_OPTS)"
	@$(VCFGMSG) "VERBOSE:" "$(VERBOSE)"
	@$(VCFGMSG) "DEBUG:" "$(DEBUG)"
	@$(VCFGMSG) "STARTUP_MAKEFILE:" "$(STARTUP_MAKEFILE)"
	@$(VCFGMSG) "CPU_BASE_TARGET:" "$(CPU_BASE_TARGET)"
	@$(VCFGMSG) "BUILD_DIR:" "$(BUILD_DIR)/$*"
	@$(VCFGMSG) "In CPU_DEVICE:" "$(CPU_DEVICE)"
	@$(VCFGMSG) "In CPU_EXEC_OFFSET:" "$(CPU_EXEC_OFFSET)"
	@$(VCFGMSG) "In CPU_DEVICE_OPTS:" "$(CPU_DEVICE_OPTS)"
	@$(VCFGMSG) "In CFLAGS:" "$(CPU_CFLAGS)"
	@$(VCFGMSG) "In CXXFLAGS:" "$(CPU_CXXFLAGS)"
	@$(VCFGMSG) "In CPPFLAGS:" "$(CPU_CPPFLAGS)"
	@$(VCFGMSG) "In ASMFLAGS:" "$(CPU_ASMFLAGS)"
	@$(VCFGMSG) "In LDFLAGS:" "$(CPU_LDFLAGS)"
	@$(VCFGMSG) "In ARFLAGS:" "$(CPU_ARFLAGS)"
	@$(VCFGMSG) "In OBJCOPYFLAGS:" "$(CPU_OBJCOPYFLAGS)"
	@$(VCFGMSG) "In OPTIMIZE:" "$(CPU_OPTIMIZE)"
	@$(VCFGMSG) "In FPGA_DEVICE:" "$(FPGA_DEVICE)"
	@$(VCFGMSG) "In FPGA_DEVICE_OPTS:" "$(FPGA_DEVICE_OPTS)"
	@$(VCFGMSG) "In NO_TESTS_DEPS:" "$(NO_TESTS_DEPS)"
	@$(VCFGMSG) "In NO_GATEWARE_UPLOAD:" "$(NO_GATEWARE_UPLOAD)"
	@$(VCFGMSG) "In NO_GATEWARE_DEPS:" "$(NO_GATEWARE_DEPS)"
	@$(VCFGMSG) "In NO_TOOLS_DEPS:" "$(NO_TOOLS_DEPS)"
	@$(VCFGMSG) 'MAKECMDGOALS:' '$(MAKECMDGOALS)'
else
	@$(MSG) "[TEST]" "$*"
endif
	$(V)$(MAKE) --directory="$(DEPENDENCY_PATH_$*)" --file="$(DEPENDENCY_PATH_$*)/Makefile" $(DEPENDENCY_OPTS_$*) \
 					$(DEPENDENCY_OPTS_$*) 'BUILD_OPTS=$(BUILD_OPTS)' 'VERBOSE=$(VERBOSE)' 'DEBUG=$(DEBUG)' 'CPU_TARGET=$*' \
 					'STARTUP_MAKEFILE=$(STARTUP_MAKEFILE)' 'CPU_BASE_TARGET=$(CPU_BASE_TARGET)' 'BUILD_DIR=$(BUILD_DIR)/$*' \
 					'IN_NO_TESTS_DEPS=$(NO_TESTS_DEPS)' 'IN_NO_GATEWARE_UPLOAD=$(NO_GATEWARE_UPLOAD)' \
 					'IN_NO_GATEWARE_DEPS=$(NO_GATEWARE_DEPS)' 'IN_NO_TOOLS_DEPS=$(NO_TOOLS_DEPS)' \
 					'IN_CPU_DEVICE=$(CPU_DEVICE)' 'IN_CPU_EXEC_OFFSET=$(CPU_EXEC_OFFSET)' 'IN_CPU_DEVICE_OPTS=$(CPU_DEVICE_OPTS)' \
 					'IN_CFLAGS=$(CPU_CFLAGS)' 'IN_CXXFLAGS=$(CPU_CXXFLAGS)' 'IN_CPPFLAGS=$(CPU_CPPFLAGS)' 'IN_ASMFLAGS=$(CPU_ASMFLAGS)' \
 					'IN_LDFLAGS=$(CPU_LDFLAGS)' 'IN_ARFLAGS=$(CPU_ARFLAGS)' 'IN_OBJCOPYFLAGS=$(CPU_OBJCOPYFLAGS)' 'IN_OPTIMIZE=$(CPU_OPTIMIZE)' \
 					'IN_FPGA_DEVICE=$(FPGA_DEVICE)' 'IN_FPGA_DEVICE_OPTS=$(FPGA_DEVICE_OPTS)' \
 					 $(MAKECMDGOALS)

# Make targets need to just call make in the directory, not caring about anything else, but still passing base config like build dir
%.make.dependency:
ifeq ($(strip $(VERBOSE)),1)
	@$(VMSG) "Building $*.make.dependency"
	@$(VCFGMSG) "TARGET:" "$*"
	@$(VCFGMSG) "PATH:" "$(DEPENDENCY_PATH_$*)"
	@$(VCFGMSG) "OPTS:" "$(DEPENDENCY_OPTS_$*)"
	@$(VCFGMSG) "BUILD_OPTS:" "$(BUILD_OPTS)"
	@$(VCFGMSG) "VERBOSE:" "$(VERBOSE)"
	@$(VCFGMSG) "DEBUG:" "$(DEBUG)"
	@$(VCFGMSG) "STARTUP_MAKEFILE:" "$(STARTUP_MAKEFILE)"
	@$(VCFGMSG) "CPU_BASE_TARGET:" "$(CPU_BASE_TARGET)"
	@$(VCFGMSG) "BUILD_DIR:" "$(BUILD_DIR)/$*"
	@$(VCFGMSG) "In CPU_DEVICE:" "$(CPU_DEVICE)"
	@$(VCFGMSG) "In CPU_EXEC_OFFSET:" "$(CPU_EXEC_OFFSET)"
	@$(VCFGMSG) "In CPU_DEVICE_OPTS:" "$(CPU_DEVICE_OPTS)"
	@$(VCFGMSG) "In CFLAGS:" "$(CPU_CFLAGS)"
	@$(VCFGMSG) "In CXXFLAGS:" "$(CPU_CXXFLAGS)"
	@$(VCFGMSG) "In CPPFLAGS:" "$(CPU_CPPFLAGS)"
	@$(VCFGMSG) "In ASMFLAGS:" "$(CPU_ASMFLAGS)"
	@$(VCFGMSG) "In LDFLAGS:" "$(CPU_LDFLAGS)"
	@$(VCFGMSG) "In ARFLAGS:" "$(CPU_ARFLAGS)"
	@$(VCFGMSG) "In OBJCOPYFLAGS:" "$(CPU_OBJCOPYFLAGS)"
	@$(VCFGMSG) "In OPTIMIZE:" "$(CPU_OPTIMIZE)"
	@$(VCFGMSG) "In FPGA_DEVICE:" "$(FPGA_DEVICE)"
	@$(VCFGMSG) "In FPGA_DEVICE_OPTS:" "$(FPGA_DEVICE_OPTS)"
	@$(VCFGMSG) "In NO_TESTS_DEPS:" "$(NO_TESTS_DEPS)"
	@$(VCFGMSG) "In NO_GATEWARE_UPLOAD:" "$(NO_GATEWARE_UPLOAD)"
	@$(VCFGMSG) "In NO_GATEWARE_DEPS:" "$(NO_GATEWARE_DEPS)"
	@$(VCFGMSG) "In NO_TOOLS_DEPS:" "$(NO_TOOLS_DEPS)"
	@$(VCFGMSG) 'MAKECMDGOALS:' '$(MAKECMDGOALS)'
else
	@$(MSG) "[MAKE]" "$*"
endif
	$(V)$(MAKE) --directory="$(DEPENDENCY_PATH_$*)" --file="$(DEPENDENCY_PATH_$*)/Makefile" $(DEPENDENCY_OPTS_$*) \
 					$(DEPENDENCY_OPTS_$*) 'BUILD_OPTS=$(BUILD_OPTS)' 'VERBOSE=$(VERBOSE)' 'DEBUG=$(DEBUG)' 'CPU_TARGET=$*' \
 					'STARTUP_MAKEFILE=$(STARTUP_MAKEFILE)' 'CPU_BASE_TARGET=$(CPU_BASE_TARGET)' 'BUILD_DIR=$(BUILD_DIR)/$*' \
 					'IN_NO_TESTS_DEPS=$(NO_TESTS_DEPS)' 'IN_NO_GATEWARE_UPLOAD=$(NO_GATEWARE_UPLOAD)' \
 					'IN_NO_GATEWARE_DEPS=$(NO_GATEWARE_DEPS)' 'IN_NO_TOOLS_DEPS=$(NO_TOOLS_DEPS)' \
 					'IN_CPU_DEVICE=$(CPU_DEVICE)' 'IN_CPU_EXEC_OFFSET=$(CPU_EXEC_OFFSET)' 'IN_CPU_DEVICE_OPTS=$(CPU_DEVICE_OPTS)' \
 					'IN_CFLAGS=$(CPU_CFLAGS)' 'IN_CXXFLAGS=$(CPU_CXXFLAGS)' 'IN_CPPFLAGS=$(CPU_CPPFLAGS)' 'IN_ASMFLAGS=$(CPU_ASMFLAGS)' \
 					'IN_LDFLAGS=$(CPU_LDFLAGS)' 'IN_ARFLAGS=$(CPU_ARFLAGS)' 'IN_OBJCOPYFLAGS=$(CPU_OBJCOPYFLAGS)' 'IN_OPTIMIZE=$(CPU_OPTIMIZE)' \
 					'IN_FPGA_DEVICE=$(FPGA_DEVICE)' 'IN_FPGA_DEVICE_OPTS=$(FPGA_DEVICE_OPTS)' \
 					 $(MAKECMDGOALS)

dependencies: $(DEPENDENCY_TARGETS)

clean-dependencies: dependencies
	@$(MSG) "[CLEAN]" "Dependencies"
	$(V)rm -f $(DEPENDENCY_LIB_PATHS)

.PHONY: dependencies clean-dependencies
