FPGA_TOOLCHAIN := yosys
FPGA_DEPLOY_TARGET := $(FPGA_TARGET).$(FPGA_BOARD).bit
FPGA_PROJECT_ARGS += -i helindustries_platform:$(FPGA_BASE_LIBRARY_PATH)/platform/lattice

YOSYS := $(YOSYS_BIN_PATH)/yosys
YOSYS_TYPE ?= ecp5
NEXTPNR := $(YOSYS_BIN_PATH)/nextpnr-$(YOSYS_TYPE)
ECPPACK := $(YOSYS_BIN_PATH)/ecppack

ECPPACK_OPTS ?=
#ECPPACK_OPTS += --idcode $(FPGA_CHIP_ID)
YOSYS_COMMAND := synth_$(YOSYS_TYPE)
YOSYS_OPTS ?=
NEXTPNR_OPTS ?=
NEXTPNR_OPTS +=  --lpf-allow-unconstrained
